name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format cppcheck

    - name: Check code formatting
      run: |
        find src tests -name "*.cpp" -o -name "*.h" | xargs clang-format -style=file --dry-run --Werror

    - name: Static analysis
      run: |
        cppcheck --enable=all --std=c++17 --error-exitcode=1 --suppress=missingIncludeSystem --suppress=unusedFunction -I src/board -I src/trie -I src/algorithm -I src/verification src/ tests/ 
